spring:

  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://47.92.211.147:3306/byzhao?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&allowPublicKeyRetrieval=true
        #    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
     username: byzhao
     password: zby123456

  redis:
    host: 47.92.211.147
    port: 6379
    database: 0
    password: zby123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
    database: MySQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.qq.com
    username: 381016296@qq.com
    password: axdymglidbvmbiai

    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
