spring:

  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://***.***.***.***:1111/zhaoboya?characterEncoding=utf-8&useSSL=true
        #    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
     username: 1111
     password: 1111

  redis:
    host: 11.11.11.11
    port: 1111
    database: 0
    password: 111111


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
    database: MySQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
