spring:

  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://111.111.111.111:3306/zhaoboya?characterEncoding=utf-8&useSSL=true
        #    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
     username: 11111111
     password: 11111111

  redis:
    host: 111.111.111.111
    port: 1111
    database: 0
    password: 11111111

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
    database: MySQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
