# 企业ID
corpid: ww8783f3dbd5f49266
# 应用密钥(短信转发应用)
secret: YD1o25EMB1I5pvRvGIgsLU_6Vby5_aVMiPgw2k0wVMg

#Token 用于回调地址认证
token: 1hjwzJhlf9SS5byieiunm7G5aRn0Iou

# 用于消息体的加密，是AES密钥的Base64编码
EncodingAESKey: Ty5DWl18tUL5Ixugrfc7ilEGYH1ogfAd6v2nzaEjdJz

# 获取登录凭证 accessToken 企业微信所有API接口都依赖accessToken来鉴权调用者身份
GET_ACCESS_TOKEN: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={corpid}&corpsecret={corpsecret}

# 创建 群聊会话
POST_APPCHAT_CREATE: https://qyapi.weixin.qq.com/cgi-bin/appchat/create?access_token={accesstoken}

# 获取 群聊会话 只允许企业自建应用调用 chatid所代表的群必须是该应用所创建
GET_APPCHAT_GET: https://qyapi.weixin.qq.com/cgi-bin/appchat/get?access_token={accesstoken}&chatid={chatid}

# 应用 推送消息 应用支持推送文本、图片、视频、文件、图文等类型。
POST_APPCHAT_SEND: https://qyapi.weixin.qq.com/cgi-bin/appchat/send?access_token={accesstoken}

# 群机器人 自动发布信息
POST_WEBHOOK_SEND: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4db83b3c-359b-48e2-9b88-7bfff9a58e99
