spring.profiles.include: database,weixin
server:
  port: 10000

spring:
  application:
    name: weixin

  servlet:
    multipart:
      max-file-size: 10MB

  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true

