spring.profiles.include: database,weixin
server:
  port: 10001

spring:
  application:
    name: weixin

  servlet:
    multipart:
      max-file-size: 10MB

localCache:
  apiCache: true #是否开启接口级本地缓存

