spring:

  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://39.96.160.110:3306/zhaoboya?characterEncoding=utf-8&useSSL=true
        #    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
     username: zhaoboya
     password: zhaoboya

  redis:
    host: 39.96.160.110
    port: 9988
    database: 0
    password: zby123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
    database: MySQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
